# Generated by Django 4.1.5 on 2023-02-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinform',
            name='stars',
        ),
    ]
