# Generated by Django 4.1.5 on 2023-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeksfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
