# Generated by Django 4.1.6 on 2023-02-16 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geeksfit', '0002_remove_training_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
